name: Health Metrics

on:
  push:
    branches:
      - master
      # other feature branches
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      commit:
        description: |
          Which commit to run the test on?
          Defaults to the tip commit on the selected branch.
      diff:
        description: |
          Whether to compare measurements against another commit?
          Defaults to false (run test without diffing).
        type: boolean
      base_commit:
        description: |
          If diffing, which commit to diff against?
          Required only if `diff` is enabled.
      pull_request:
        description: |
          If diffing, which pull request to post the results to?
          Required only if `diff` is enabled.

jobs:
  startup_time:
    name: Startup Time
    runs-on: ubuntu-latest
    steps:
      - name: Output inputs
        run: |
          echo 'commit: ${{ inputs.commit }}'
          echo 'diff: ${{ inputs.diff }}'
          echo 'base_commit: ${{ inputs.base_commit }}'
          echo 'pull_request: ${{ inputs.pull_request }}'
