name: Health Metrics

on:
  push:
    branches:
      - master
      # other feature branches
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      commit:
        description: |
          Which commit to run the test on?
          Defaults to the tip commit on the selected branch.
      diff:
        description: Compare against another commit? Defaults to false.
        type: boolean
      base_commit:
        description: If diffing, which commit to compare against?
      pull_request:
        description: If diffing, which pull request to post the results to?

jobs:
  startup_time:
    name: Startup Time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:

      - name: Determine test metadata
        uses: actions/github-script@v6
        with:
          script: |
            if (context.github.event_name === 'push') {
              core.setOutput('continue', true)
              core.setOutput('commit', context.github.sha)
              core.setOutput('diff', false)
              core.setOutput('base_commit', null)
              core.setOutput('pull_request', null)
            } else if (context.github.event_name === 'pull_request') {
              if (context.github.event.label.name === 'startup-time') {
                core.setOutput('continue', true)
                core.setOutput('commit', context.github.sha)
                core.setOutput('diff', true)
                core.setOutput('base_commit', null)
                core.setOutput('pull_request', context.github.event.number)
              }
            }
      - name: Output inputs
        run: |
          echo 'commit: ${{ inputs.commit }}'
          echo 'diff: ${{ inputs.diff }}'
          echo 'base_commit: ${{ inputs.base_commit }}'
          echo 'pull_request: ${{ inputs.pull_request }}'
